CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

TARGET = loramac
CONTIKI = ../..

include $(CONTIKI)/Makefile.dir-variables
MODULES += $(CONTIKI_NG_SERVICES_DIR)/shell

include $(CONTIKI)/Makefile.include
